### ISSUE TITLE
Compass master broken with sass > 3.1.0.alpha.32

### ISSUE THREAD

**Issue by slbug** [Compass/compass#223]
It works using sass 3.1.0.alpha.32, but broken with 3.1.0.alpha.33 and 3.1.0.alpha.34

<pre>
/Users/user/.rvm/gems/ruby-head/gems/sass-3.1.0.alpha.34/lib/sass/plugin/configuration.rb:116:in `join': can't convert nil into String (TypeError)
        from /Users/user/.rvm/gems/ruby-head/gems/sass-3.1.0.alpha.34/lib/sass/plugin/configuration.rb:116:in `normalize_template_location!'
        from /Users/user/.rvm/gems/ruby-head/gems/sass-3.1.0.alpha.34/lib/sass/plugin/configuration.rb:104:in `template_location_array'
        from /Users/user/.rvm/gems/ruby-head/gems/sass-3.1.0.alpha.34/lib/sass/plugin/compiler.rb:338:in `template_locations'
        from /Users/user/.rvm/gems/ruby-head/gems/sass-3.1.0.alpha.34/lib/sass/plugin/compiler.rb:334:in `load_paths'
        from /Users/user/.rvm/gems/ruby-head/gems/sass-3.1.0.alpha.34/lib/sass/plugin/compiler.rb:289:in `engine_options'
        from /Users/user/.rvm/gems/ruby-head/gems/sass-3.1.0.alpha.34/lib/sass/plugin.rb:111:in `method_missing'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/compass-d68ee5d11a5f/lib/compass/configuration/helpers.rb:62:in `block in configure_sass_plugin!'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/compass-d68ee5d11a5f/lib/compass/configuration/helpers.rb:61:in `each'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/compass-d68ee5d11a5f/lib/compass/configuration/helpers.rb:61:in `configure_sass_plugin!'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/compass-d68ee5d11a5f/lib/compass/app_integration/rails.rb:41:in `initialize!'
        from /Users/user/Work/testapp/config/initializers/compass.rb:3:in `<top (required)>'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:235:in `load'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:235:in `block in load'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:235:in `load'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/engine.rb:511:in `block (2 levels) in <class:Engine>'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/engine.rb:510:in `each'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/engine.rb:510:in `block in <class:Engine>'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/initializable.rb:25:in `instance_exec'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/initializable.rb:25:in `run'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/initializable.rb:50:in `block in run_initializers'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/initializable.rb:49:in `each'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/initializable.rb:49:in `run_initializers'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/application.rb:93:in `initialize!'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /Users/user/Work/testapp/config/environment.rb:5:in `<top (required)>'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:239:in `require'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:239:in `block in require'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/activesupport/lib/active_support/dependencies.rb:239:in `require'
        from /Users/user/Work/testapp/config.ru:3:in `block in <main>'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rack-85ca454e6143/lib/rack/builder.rb:46:in `instance_eval'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rack-85ca454e6143/lib/rack/builder.rb:46:in `initialize'
        from /Users/user/Work/testapp/config.ru:1:in `new'
        from /Users/user/Work/testapp/config.ru:1:in `<main>'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rack-85ca454e6143/lib/rack/builder.rb:35:in `eval'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rack-85ca454e6143/lib/rack/builder.rb:35:in `parse_file'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rack-85ca454e6143/lib/rack/server.rb:163:in `app'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rack-85ca454e6143/lib/rack/server.rb:259:in `wrapped_app'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rack-85ca454e6143/lib/rack/server.rb:211:in `start'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/commands/server.rb:65:in `start'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/commands.rb:52:in `block in <top (required)>'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/commands.rb:47:in `tap'
        from /Users/user/.rvm/gems/ruby-head/bundler/gems/rails-d891ad4e92c4/railties/lib/rails/commands.rb:47:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
</pre>

**Comment by chriseppstein** [comment]
fixed on master.

**Comment by nex3** [comment]
What was the cause of this exactly? I'd like to try to make the new Rails 3 configuration stuff in Sass work without completely breaking existing configuration of stuff like Compass.

**Comment by chriseppstein** [comment]
Compass projects are fine. It was breakage in the compass extensions to sass when Haml::Util went away and lists were added.

**Comment by slbug** [comment]
still not working. getting same error.

my Gemfile

<pre>
gem 'haml'
gem 'sass'
gem 'compass', :git => 'git://github.com/chriseppstein/compass.git', :branch => 'master'
</pre>


bundle list:

<pre>
  * compass (0.11.alpha.0.2048309 2048309)
  * haml (3.0.24)
  * sass (3.1.0.alpha.34)
</pre>


config/compass.rb

<pre>
project_type = :rails
project_path = Compass::AppIntegration::Rails.root
http_path = "/"
css_dir = "public/stylesheets"
sass_dir = "app/stylesheets"
environment = Compass::AppIntegration::Rails.env
</pre>

**Comment by chriseppstein** [comment]
I cannot reproduce your particular issue. I ran thru the following steps:
1. rails new asdf
2. cd asdf
3. Add entries to gemfile from above
4. bundle install
5. bundle exec compass init rails
6. rails console
7. puts Sass::Plugin.options[:template_location]

It looks like you have an initializer in your setup. Compass no longer delivers an initializer to new rails projects -- it uses a Railtie instead. How did yours get there? can you paste the contents of it? Perhaps having that causes the issue...

**Comment by slbug** [comment]
yes, i have initializer

<pre>
require 'compass'
require 'compass/app_integration/rails'
Compass::AppIntegration::Rails.initialize!
</pre>

**Comment by chriseppstein** [comment]
By the way, the specific issue appears to be that there's a template location of nil => nil registered in your app. We need to figure out what is adding that.

**Comment by chriseppstein** [comment]
I tested with the initializer. everything still works ok for me.

<pre>
Gems included by the bundle:
  * abstract (1.0.0)
  * actionmailer (3.0.3)
  * actionpack (3.0.3)
  * activemodel (3.0.3)
  * activerecord (3.0.3)
  * activeresource (3.0.3)
  * activesupport (3.0.3)
  * arel (2.0.4)
  * builder (2.1.2)
  * bundler (1.0.7)
  * compass (0.11.alpha.0.2048309 2048309)
  * erubis (2.6.6)
  * haml (3.0.24)
  * i18n (0.4.2)
  * mail (2.2.10)
  * mime-types (1.16)
  * polyglot (0.3.1)
  * rack (1.2.1)
  * rack-mount (0.6.13)
  * rack-test (0.5.6)
  * rails (3.0.3)
  * railties (3.0.3)
  * rake (0.8.7)
  * sass (3.1.0.alpha.34)
  * sqlite3-ruby (1.3.2)
  * thor (0.14.6)
  * treetop (1.4.9)
  * tzinfo (0.3.23)
</pre>

**Comment by slbug** [comment]
I removed initializer and still have same issue.

**Comment by chriseppstein** [comment]
@slbug, I'm out of ideas and cannot reproduce this issue. Please provide steps to reproduce from scratch or provide an archive of an application that demonstrates the issue.

**Comment by slbug** [comment]
I've found problem. it fails only on rails master. dunno why.

**Comment by slbug** [comment]
Seems like because of this commit - https://github.com/rails/rails/commit/32a5b49911b88e8e410583d382e8253004abce50#diff-6

**Comment by chriseppstein** [comment]
Interesting. I can reproduce the problem now with this Gemfile:

<pre>
gem 'sass', :path => "/Users/chris/Projects/sass"
gem 'compass', :git => 'git://github.com/chriseppstein/compass.git', :branch => 'master'
gem 'rails', :git => 'git://github.com/rails/rails.git', :branch => 'master'
</pre>

**Comment by chriseppstein** [comment]
But I have to stop working on this now... (day job)

**Comment by nex3** [comment]
This was caused by the new Sass/Rails integration work. I've pushed a change that should fix it.

**Comment by chriseppstein** [comment]
Thanks, Nathan.
